# Site settings
title:          const
description:    "Blog about study and life."
baseurl:        ""
domainUrl:      "https://blog.chenkun.me"

# 菜单
menu:
  - title: Archives
    url: /
  - title: Tags
    url: /tags
  - title: Wiki
    url: /wiki
  - title: About
    url: /about

collections:
  wiki:
    output: true
    permalink: /wiki/:path/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink: /blog/:year/:month/:day/:title

# kramdown
kramdown:
  # set toc levels
  toc_levels: 1..3

# 10 posts per page
paginate:       20
paginate_path:  "p-:num"

exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock']

# compress sass code
sass:
  sass_dir:     /sass
  style:        compressed

  # compress html code
compress_html:
  blanklines:       true

# Valine comment system
valine:
  appid:  lEIv1VK2U7GjS8qxH71A5nkS-MdYXbMMI # your leancloud app id
  appkey: 2G2miTD0y1N95pWubaI1UgqG # your leancloud app key
  placeholder: 留下邮箱可收到邮件回复 # comment box placeholder
  notify: false # mail notifier
  verify: false # Verification code
  avatar: monsterid  # gravatar style
  # pageSize: 10 # pagination size
  serverURLs: https://leiv1vk2.api.lncldglobal.com

  ## not sure how to set in _config.yml
  # meta is set in _include/ext-comment.html
  # meta: ["nick", "mail"]      # custom comment header
